name: Schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Build static feeds site
    permissions:
      contents: write
      issues: write
    steps:
      - name: Run Action
        uses: llun/feeds@4.6.3
